// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLATVLeyYLBgDAJsC2bCmiouCgUIU5c_I',
    appId: '1:996204991048:web:a150e53639c85aabb17e7d',
    messagingSenderId: '996204991048',
    projectId: 'ai-resume-builder-18e2f',
    authDomain: 'ai-resume-builder-18e2f.firebaseapp.com',
    storageBucket: 'ai-resume-builder-18e2f.firebasestorage.app',
    measurementId: 'G-Z415WECLN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1PSJm7YuSj5GKI2IoygIWHBxsYC4Y11g',
    appId: '1:996204991048:android:6501af50af3e1f5bb17e7d',
    messagingSenderId: '996204991048',
    projectId: 'ai-resume-builder-18e2f',
    storageBucket: 'ai-resume-builder-18e2f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLATVLeyYLBgDAJsC2bCmiouCgUIU5c_I',
    appId: '1:996204991048:web:c12839fceff9ecc2b17e7d',
    messagingSenderId: '996204991048',
    projectId: 'ai-resume-builder-18e2f',
    authDomain: 'ai-resume-builder-18e2f.firebaseapp.com',
    storageBucket: 'ai-resume-builder-18e2f.firebasestorage.app',
    measurementId: 'G-99QBTHJJNP',
  );
}
